### ISSUE TITLE
How to setup replica set?

### ISSUE THREAD

**Issue by mewben** [dokku/dokku-mongo#110]
I'm sorry if this is not the right place to ask. :(

Is there a way to setup dokku-mongo using replica sets? I can't find a dokku specific way to set this up.

Thank you.

**Comment by josegonzalez** [comment]
There is some background in [this issue](https://github.com/dokku/dokku-mongo/issues/88), but generally speaking, this functionality isn't really in the scope of this plugin.

If this is something you'd like to sponsor the work for, feel free to reach out via email. Otherwise, you're also free to submit a pull request implementing this functionality.
