### ISSUE TITLE
Expose with a custom domain, not IP address?

### ISSUE THREAD

**Issue by tiltowait** [dokku/dokku-mongo#152]
Using 1.17.5, is it possible to `expose` the MongoDB container, but using a domain name instead of an IP address?

**Comment by josegonzalez** [comment]
Not really. You'd need a TCP proxy for that (with SNI), and Dokku doesn't currently have any built-in facility for that.

What exactly are you trying to do?

**Comment by tiltowait** [comment]
Just trying to make a nicer connection string. It's not a big deal.

**Comment by josegonzalez** [comment]
Yeah I dont think thats super possible. We have this [service-proxy](https://github.com/dokku/service-proxy) project for when the service exposes an admin panel, but nothing for TCP unfortunately.

You can use any domain associated with your server's IP address instead of the server's IP. So long as the address is exposed, it should be pretty much the same.

**Comment by tiltowait** [comment]
I think that will probably work, then. Thanks!
